---
title: "Actives analysis"
author: "Summerge"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

### Loading and preprocessing the data
```{r echo = TRUE}
setwd("/Users/summerge/Documents/Learning R/RR")
library(dplyr);library(ggplot2);library(knitr);library(mice)
actives_data <- read.csv("activity.csv")
by_date_actives <- group_by(actives_data, date)
totalsteps_preday <- summarise(by_date_actives, steps = sum(steps, na.rm = T))
```
###Mean total number of steps taken per day

```{r echo = TRUE}
summary(totalsteps_preday$steps)
```

### Average daily activity pattern
#### Time series plot of the 5-minute interval
```{r echo = T, fig.height=5, fig.width = 7.5, fig.show='hold'}
by_interval <- group_by(actives_data, interval)
meansteps_preinterval <- summarise(by_interval, steps = mean(steps, na.rm = T))
qplot(interval, steps, data = meansteps_preinterval, geom = "line")

```

####maximum number of steps
```{r, echo = T}
meansteps_preinterval[which.max(meansteps_preinterval$steps),]
```

###Imputing missing values
```{r echo = T, fig.show='hold', fig.height=5, fig.width=7.5}
actives_imp <- mice(actives_data, seed = 1234, print=FALSE)
actives_new <- complete(actives_imp)
by_actives_new <- group_by(actives_new, date)
actives_total <- summarise(by_actives_new, steps = sum(steps))
qplot(steps, data = actives_total,geom = "histogram", binwidth = 2000)
```
```{r, echo = T}
summary(actives_total$steps)
```
```{r, echo=TRUE, fig.height=5, fig.width=7.5, fig.show='hold'}
weekends <- function(date){
  t = weekdays(date)
  ifelse((t == "Sunday") | (t == "Saturday"), "weekend", "weekday")
}
actives_new <- transform(actives_new, date = as.Date(date))
actives_new <- transform(actives_new, week = weekends(date))
by_week <- group_by(actives_new, week, interval)
by_week <- summarise(by_week, steps = sum(steps))
qplot(interval, steps, data = by_week, facets = week~., geom = "line")
```
